    // stage prime (39-bit, 2-adicity 26, q_log 129)
    class B60FpParamsBaseS1 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 549286051841ULL;
    };
    class B60CbigS1 : public B60FpParamsBaseS1 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 129;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (39-bit, 2-adicity 27, q_log 129)
    class B60FpParamsBaseS2 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 549084725249ULL;
    };
    class B60CbigS2 : public B60FpParamsBaseS2 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 129;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (39-bit, 2-adicity 27, q_log 129)
    class B60FpParamsBaseS3 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 548816289793ULL;
    };
    class B60CbigS3 : public B60FpParamsBaseS3 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 129;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (56-bit, 2-adicity 26, q_log 146)
    class B60FpParamsBaseS4 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 72057593031294977ULL;
    };
    class B60CbigS4 : public B60FpParamsBaseS4 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 146;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (56-bit, 2-adicity 26, q_log 146)
    class B60FpParamsBaseS5 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 72057592225988609ULL;
    };
    class B60CbigS5 : public B60FpParamsBaseS5 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 146;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (56-bit, 2-adicity 27, q_log 146)
    class B60FpParamsBaseS6 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 72057590950920193ULL;
    };
    class B60CbigS6 : public B60FpParamsBaseS6 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 146;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (56-bit, 2-adicity 26, q_log 146)
    class B60FpParamsBaseS7 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 72057590346940417ULL;
    };
    class B60CbigS7 : public B60FpParamsBaseS7 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 146;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 27, q_log 150)
    class B60FpParamsBaseS8 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921504204193793ULL;
    };
    class B60CbigS8 : public B60FpParamsBaseS8 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 27, q_log 150)
    class B60FpParamsBaseS9 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921499909226497ULL;
    };
    class B60CbigS9 : public B60FpParamsBaseS9 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 31, q_log 150)
    class B60FpParamsBaseS10 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921493869428737ULL;
    };
    class B60CbigS10 : public B60FpParamsBaseS10 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 26, q_log 150)
    class B60FpParamsBaseS11 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921492728578049ULL;
    };
    class B60CbigS11 : public B60FpParamsBaseS11 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 29, q_log 150)
    class B60FpParamsBaseS12 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921490111332353ULL;
    };
    class B60CbigS12 : public B60FpParamsBaseS12 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 26, q_log 150)
    class B60FpParamsBaseS13 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921488702046209ULL;
    };
    class B60CbigS13 : public B60FpParamsBaseS13 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 27, q_log 150)
    class B60FpParamsBaseS14 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921488098066433ULL;
    };
    class B60CbigS14 : public B60FpParamsBaseS14 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (60-bit, 2-adicity 26, q_log 150)
    class B60FpParamsBaseS15 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 1152921487225651201ULL;
    };
    class B60CbigS15 : public B60FpParamsBaseS15 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 150;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (61-bit, 2-adicity 26, q_log 151)
    class B60FpParamsBaseS16 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 2305843009146585089ULL;
    };
    class B60CbigS16 : public B60FpParamsBaseS16 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 151;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (61-bit, 2-adicity 28, q_log 151)
    class B60FpParamsBaseS17 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 2305843007334645761ULL;
    };
    class B60CbigS17 : public B60FpParamsBaseS17 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 151;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (61-bit, 2-adicity 26, q_log 151)
    class B60FpParamsBaseS18 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 2305843004314746881ULL;
    };
    class B60CbigS18 : public B60FpParamsBaseS18 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 151;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
    // stage prime (61-bit, 2-adicity 29, q_log 151)
    class B60FpParamsBaseS19 {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 2305843003308113921ULL;
    };
    class B60CbigS19 : public B60FpParamsBaseS19 {
    public:
        static constexpr const uint32_t n = 8192;
        static constexpr const uint64_t q_log = 151;
        static constexpr const uint128_t q_int = 0;
        static constexpr const uint128_t rescale_q = 0;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };
