        else if constexpr (ParamsBase::p_int == 549286051841ULL) { // 39-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(6);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)282980918334ULL);
        }
        else if constexpr (ParamsBase::p_int == 549084725249ULL) { // 39-bit stage
            Fp_type::s = 27;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)374264236563ULL);
        }
        else if constexpr (ParamsBase::p_int == 548816289793ULL) { // 39-bit stage
            Fp_type::s = 27;
            Fp_type::multiplicative_generator = Fp_type(10);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)149882511768ULL);
        }
        else if constexpr (ParamsBase::p_int == 72057593031294977ULL) { // 56-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)65071237797831546ULL);
        }
        else if constexpr (ParamsBase::p_int == 72057592225988609ULL) { // 56-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)67887714404322108ULL);
        }
        else if constexpr (ParamsBase::p_int == 72057590950920193ULL) { // 56-bit stage
            Fp_type::s = 27;
            Fp_type::multiplicative_generator = Fp_type(13);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)29409214198148653ULL);
        }
        else if constexpr (ParamsBase::p_int == 72057590346940417ULL) { // 56-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(5);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)19183525055538386ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921504204193793ULL) { // 60-bit stage
            Fp_type::s = 27;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)659455761907629336ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921499909226497ULL) { // 60-bit stage
            Fp_type::s = 27;
            Fp_type::multiplicative_generator = Fp_type(5);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)933951409215174542ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921493869428737ULL) { // 60-bit stage
            Fp_type::s = 31;
            Fp_type::multiplicative_generator = Fp_type(15);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)812328637497054208ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921492728578049ULL) { // 60-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)374331786710204250ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921490111332353ULL) { // 60-bit stage
            Fp_type::s = 29;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)582675994714024254ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921488702046209ULL) { // 60-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)63246419228846140ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921488098066433ULL) { // 60-bit stage
            Fp_type::s = 27;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)1084383053072129134ULL);
        }
        else if constexpr (ParamsBase::p_int == 1152921487225651201ULL) { // 60-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(19);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)982782510870060297ULL);
        }
        else if constexpr (ParamsBase::p_int == 2305843009146585089ULL) { // 61-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)1139340916286364867ULL);
        }
        else if constexpr (ParamsBase::p_int == 2305843007334645761ULL) { // 61-bit stage
            Fp_type::s = 28;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)2213818387612703048ULL);
        }
        else if constexpr (ParamsBase::p_int == 2305843004314746881ULL) { // 61-bit stage
            Fp_type::s = 26;
            Fp_type::multiplicative_generator = Fp_type(3);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)2286490874222697896ULL);
        }
        else if constexpr (ParamsBase::p_int == 2305843003308113921ULL) { // 61-bit stage
            Fp_type::s = 29;
            Fp_type::multiplicative_generator = Fp_type(6);
            Fp_type::root_of_unity = Fp_type((unsigned __int128)2162902039495734269ULL);
        }
